reviews:
  auto_review:
    enabled: true

  high_level_summary: true
  poem: false
  review_status: true

  collapse_walkthrough: false

  path_filters:
    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
